// package public types exports
export * from './common';
export * from './WebApp';
export type {
  CallEventCallbackHandler,
  ClipboardTextReceivedWebViewEventData,
  DataSendEventData,
  ImpactHapticFeedbackData,
  InitParams,
  InvoiceClosedWebViewEventData,
  NotificationHapticFeedbackData,
  OpenInvoiceEventData,
  OpenLinkEventData,
  OpenPopupEventData,
  OpenTgLinkEventData,
  PaymentFormSubmitEventData,
  PopupClosedWebViewEventData,
  PostEventCallback,
  PostEventCallbackData,
  QrTextReceivedWebViewEventData,
  RedTextFromClipboardEventData,
  ResizeFrameEventData,
  SelectionChangeHapticFeedbackData,
  SetBackgroundColorEventData,
  SetHeaderColorEventData,
  SetupBackButtonEventData,
  SetupClosingBehaviorEventData,
  SetupMainButtonEventData,
  SwitchInlineQueryEventData,
  ThemeChangedWebViewEventData,
  TriggerHapticFeedbackEventData,
  ViewportChangedWebViewEventData,
  WebView,
  WebViewEvent,
} from './WebView';
